package main

import (
	"embed"
	"fmt"
	"io/fs"
	"log"
	"net/http"
)

//go:embed all:frontend/dist
var preactFS embed.FS

func main() {
	// setup cache path flag
	config := loadConfig()

	// Root at the `dist` folder generated by the preact app.
	distFS, err := fs.Sub(preactFS, "frontend/dist")
	if err != nil {
		log.Fatal(err)
	}

	// The static preact app will be served under `/`.
	http.Handle("/", http.FileServer(http.FS(distFS)))
	// The API will be served under `/api`.
	http.HandleFunc("/api/v1/", handleAPI)

	// Start HTTP server at port.
	log.Printf("Starting HTTP server at http://localhost:%d ...\n", config.port)
	err = http.ListenAndServe(
		fmt.Sprintf(":%d", config.port),
		nil,
	)
	if err != nil {
		log.Fatal(err)
	}
}

func handleAPI(w http.ResponseWriter, _ *http.Request) {
	fmt.Fprintf(w, "Hello, from api!")
}
